### ISSUE TITLE
UIの改善(ボタンの感じ・自転車ピンの大きさ・表示の修正)

### ISSUE THREAD

**Issue by katoyu** [namihira33/Hello_Melonpan#13]
- [x] ボタンの表示の修正（黒ずむ、小さい）
- [x] 自転車ピンが小さいので大きくする（画像の変更で対応？）
- [x] 位置情報取得してることがわかると良い
- [x] 地図の上側をフューチャーブルーでライン取りする

**Comment by namihira33** [comment]
水3・4限で終わりました！
