### ISSUE TITLE
水曜３限までにすること

### ISSUE THREAD

**Issue by namihira33** [namihira33/Hello_Melonpan#7]
- [ ] データを集める(ユーザーデータ・計測データを集められる)

- [ ] UIの改善(ボタンの感じ・自転車ピンの大きさ・表示の修正)

- [ ] データベースにtime追加 -> 経路順で表示できるようにする。

- [ ] 日付から拾ってきたデータをもとに経路の線表示(1週間先までできると良い)

- [ ] 全ユーザーの経路を調べてそれを経路で線表示

(滝波案)

**Comment by katoyu** [comment]
分散させたのでClose
